services:
  - type: web
    name: pharma-guard-backend
    env: python
    region: ohio # US East (Ohio)
    plan: free # Optional, defaults to starter for paid accounts, but free is available for individual webservices
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GROQ_API_KEY
        sync: false # User must provide this in dashboard
